'''
Splits logs generated by 'learn rules' module by subjects
keeping the original files intact.
'''


import argparse
import re
from datetime import datetime
from pathlib import Path
from typing import List


# UTILS
def read_text(fpath):
  with open(fpath) as fin:
    return fin.read()

def write_text(fpath, text):
  with open(fpath, 'w') as fout:
    fout.write(text)


# INTERNAL FUNCTIONS
def get_subject_names() -> List[str]:
  '''
  RETURN a list of subject names from the log file
  by searching for the <START> tag.
  The subject name is the text between the <START> and </START> tags.
  '''
  global LOG_FNAME, RE_START_TAG
  logfile = read_text(LOG_FNAME)
  matches = re.finditer(RE_START_TAG, logfile)
  subject_names = [m.group(1).strip() for m in matches]
  return subject_names


def process_subject_logs(subject_name: str, log_lines: List[str], save_dir: Path) -> None:
  '''
  Given a subject name, slice the log lines between the <START> and </END> tags
  for that subject and save it to a file in the specified directory.
  '''
  startline = log_lines.index(START_TAG.format(subject_name=subject_name))
  endline = log_lines.index(END_TAG.format(subject_name=subject_name))
  subject_logs = '\n'.join(log_lines[startline:endline+1])

  assert save_dir.is_dir(), 'save directory should be a directory'
  assert save_dir.exists(), 'save directory should exist'

  # write logs
  write_text(save_dir / f'pirel-{subject_name}.log', subject_logs)


RE_START_TAG = r'<START>(.{5})</START>'
START_TAG = '<START>{subject_name}</START>'
END_TAG = '<END>{subject_name}</END>'

CWD = Path('.')
LOG_FNAME = CWD / 'pirel.log'
SUBJECT_LOGS_SAVE_DIR = CWD / 'learn-rules'


def main():
  global SUBJECT_LOGS_SAVE_DIR, LOG_FNAME
  parser = argparse.ArgumentParser(description='Helper functions for Makefile')
  parser.add_argument('mode', type=str, help='mode [split]')
  args = parser.parse_args()

  if args.mode == 'split':
    log_lines = read_text(LOG_FNAME).splitlines()
    subject_names = get_subject_names()
    for subject_name in subject_names:
      process_subject_logs(subject_name, log_lines, SUBJECT_LOGS_SAVE_DIR)
  else:
    raise ValueError(f'Unknown mode: {args.mode}')


if __name__ == '__main__':
  main()
