'''
Analyzes logs generated by p_learn_apply_rules and outputs statistics.
'''


import argparse
import json
import re
import yaml
from typing import List

import p_consts
import p_tree_log as ptlog
import p_utils


def load_log_yaml(subject_name: str) -> ptlog.Subject:
  '''
  Loads a YAML file containing the log data for a subject from p_consts.LEARN_RULES_LOGS_DIR.
  YAML log files are saved by p_learn_apply_rules incrementally. Check the p_learn_apply_rules.py.

  Learn phase: (contains only learn phase logs)
  1. if success: {subject.name}_tree_log_learn_phase_success.yaml
  2. if    fail: {subject.name}_tree_log_learn_phase_fail.yaml

  Apply phase: (contains both learn and apply phase logs)
  1. if success: {subject.name}_tree_log_apply_phase_success.yaml
  2. if    fail: {subject.name}_tree_log_apply_phase_fail.yaml

  Overall log file:
  tree-log-{conf["benchmark_name"]}.yaml
  '''

  learn_success_fpaths = list(p_consts.LEARN_RULES_LOGS_DIR.glob(
    f'{subject_name}_tree_log_learn_phase_success.yaml'))
  learn_fail_fpaths = list(p_consts.LEARN_RULES_LOGS_DIR.glob(
    f'{subject_name}_tree_log_learn_phase_fail.yaml'))

  apply_success_fpaths = list(p_consts.LEARN_RULES_LOGS_DIR.glob(
    f'{subject_name}_tree_log_apply_phase_success.yaml'))
  apply_fail_fpaths = list(p_consts.LEARN_RULES_LOGS_DIR.glob(
    f'{subject_name}_tree_log_apply_phase_fail.yaml'))

  if apply_success_fpaths or apply_fail_fpaths:
    assert len(apply_success_fpaths) + len(apply_fail_fpaths) == 1, 'apply phase: success XOR fail expected'
    fpaths = apply_success_fpaths + apply_fail_fpaths
    print('Using apply phase log file:', fpaths[0])
  else:
    assert len(learn_success_fpaths) + len(learn_fail_fpaths) == 1, 'learn phase: success XOR fail expected'
    fpaths = learn_success_fpaths + learn_fail_fpaths
    print('Using learn phase log file:', fpaths[0])

  assert len(fpaths) == 1, f'Expected exactly one file for subject {subject_name}, found {len(fpaths)}'
  yaml_text = p_utils.read_text(fpaths[0])
  yaml_obj = yaml.safe_load(yaml_text)
  subject_stats = ptlog.Subject.from_dict(yaml_obj)
  return subject_stats


def retrieve_subject_names() -> List[str]:
  '''
  Retrieves subject names from user input or cached file.
  If the cached file exists, it reads the subject names from there.
  If not, it prompts the user to enter subject names.
  '''
  subject_names_fpath = p_consts.TMP_DIR / 'subject-names.txt'
  if subject_names_fpath.exists():
    print(f'Using cached subject names from {subject_names_fpath}')
    with open(subject_names_fpath, 'r') as f:
      subject_names = [line.strip() for line in f if line.strip()]
    if len(subject_names) > 0:
      return subject_names
    print('Cached subject names file is empty, prompting for input.')

  subject_names = []
  print('Enter subjects names as copied from Google Sheets: (ENTER twice to finish)')
  while True:
    user_input = input()
    if user_input == '':
      break
    subject_names.append(user_input.strip())
  if not subject_names:
    raise ValueError('No subjects names provided.')
  return subject_names


def mode_gsheet():
  '''
  Mode for processing logs and writing results to Google Sheets.
  '''
  output_fpath = p_consts.TMP_DIR / 'gsheet.json'
  with open(output_fpath, 'w') as f:
    subject_names = retrieve_subject_names()
    for subject_name in subject_names:
      print(f'Processing subject: {subject_name}')
      lsubject = load_log_yaml(subject_name)
      output_fpath.write_text(json.dumps(lsubject.get_general_stats(), indent=2))

  print(f'GSheet stats written to {output_fpath}')


def get_args():
  parser = argparse.ArgumentParser(description='Analyze logs')
  parser.add_argument('--mode', default='gsheet', help='Mode of operation', choices=['gsheet'])
  return parser.parse_args()


def main():
  args = get_args()
  if args.mode == 'gsheet':
    mode_gsheet()
  else:
    raise ValueError(f'Unknown mode: {args.mode}')


if __name__ == '__main__':
  main()
