'''
Analyzes logs generated by p_learn_apply_rules and outputs statistics.
'''


import argparse
import yaml
from pathlib import Path
from typing import List, Optional, Union

import p_consts
import p_ruleset
import p_tree_log as ptlog
import p_utils


logger = p_utils.setup_logger(__name__)


# COMMON FUNCTIONS
def _normalize_path(path: Union[str, Path]) -> Path:
  '''
  Normalizes a file path by expanding user symbols and resolving to an absolute path.
  PRE path is either relative to CWD or absolute.
  '''
  if isinstance(path, str):
    path = Path(path)
  if not path.is_absolute():
    path = p_consts.ROOT_DIR / path
  return path.expanduser().resolve()


def load_lsubject(subject_log_fpath: Path) -> ptlog.Subject:
  '''
  Loads a YAML file containing the log data for a subject.
  '''
  assert subject_log_fpath is not None, 'subject_log_fpath should not be None'
  assert subject_log_fpath.exists(), f'subject_log_fpath does not exist: {subject_log_fpath}'
  assert subject_log_fpath.suffix == '.yaml', 'subject_log_fpath should be a .yaml file'
  yaml_text = p_utils.read_text(subject_log_fpath)
  yaml_obj = yaml.safe_load(yaml_text)
  lsubject = ptlog.Subject.from_dict(yaml_obj)
  return lsubject


def load_rulesets(
  subject_names: List[str],
  logs_dir: Path,
) -> p_ruleset.Ruleset:
  '''
  Loads rulesets from the log files of the given subjects.
  If multiple subject_names are given, returns a ruleset object
  that contains a union of all rulesets.
  PRE len(subject_names) > 0
  PRE application phase is successful for all subjects in subject_names
  '''
  assert len(subject_names) > 0, 'subject_names should not be empty'
  assert logs_dir.exists(), f'logs_dir does not exist: {logs_dir}'

  # bootstrap by loading the first subject's ruleset
  ruleset_serialized = get_ruleset_serialized(subject_names[0], logs_dir)
  ruleset = p_ruleset.Ruleset.from_dict(ruleset_serialized)

  for idx, subject_name in enumerate(subject_names[1:], start=2):
    logger.debug(f'[{idx}/{len(subject_names)}] Extending ruleset with rules from subject: {subject_name}')
    subject_ruleset_serialized = get_ruleset_serialized(subject_name, logs_dir)
    subject_ruleset = p_ruleset.Ruleset.from_dict(subject_ruleset_serialized)
    ruleset.extend(subject_ruleset)

  return ruleset


def get_ruleset_serialized(subject_name: str, logs_dir: Path) -> dict:
  '''
  Returns the ruleset as a serialized dict from the log dir.
  Serialized ruleset is saved by p_learn_apply_rules as
  {subject_name}_validated_rules.json and {subject_name}_learned_rules.json.
  '''
  fpaths = list(logs_dir.glob(f'{subject_name}_validated_rules.json'))
  assert len(fpaths) == 1, f'{subject_name}_validated_rules.json not found in {logs_dir}'
  ruleset_serialized = p_utils.read_json(fpaths[0])
  return ruleset_serialized


def get_subject_src_program(
  subject_name: str,
  benchmark_name: str,
) -> str:
  '''
  Returns the source program for a given subject name.
  '''
  if benchmark_name == 'gfg':
    subject_fpaths = list(p_consts.GFG_BENCHMARK_DIR.glob(f'{subject_name}_*.py'))
    assert len(subject_fpaths) == 1, f'Expected exactly one file for subject {subject_name}'
    return p_utils.read_text(subject_fpaths[0])

  raise NotImplementedError(f'{benchmark_name} is not supported')


def get_subject_tree_log_fpath(subject_name: str, logs_dir: Path) -> Optional[Path]:
  '''
  Returns the path to the YAML log file from which the
  subject's hierarchical log data can be loaded.

  YAML log files are saved by p_learn_apply_rules incrementally.
  The default save location is p_consts.LEARN_RULES_LOGS_DIR.
  Check p_learn_apply_rules.py for details.

  Learn phase: (contains only learn phase logs)
  1. if success: {subject_name}_tree_log_learn_phase_success.yaml
  2. if    fail: {subject_name}_tree_log_learn_phase_fail.yaml

  Apply phase: (contains both learn and apply phase logs)
  1. if success: {subject_name}_tree_log_apply_phase_success.yaml
  2. if    fail: {subject_name}_tree_log_apply_phase_fail.yaml

  Overall log file: (contains both learn and apply phase logs for all subjects)
  tree-log-{conf["benchmark_name"]}.yaml
  '''

  apply_success_fpaths = list(logs_dir.glob(
    f'{subject_name}_tree_log_apply_phase_success.yaml'))
  apply_fail_fpaths = list(logs_dir.glob(
    f'{subject_name}_tree_log_apply_phase_fail.yaml'))

  learn_success_fpaths = list(logs_dir.glob(
    f'{subject_name}_tree_log_learn_phase_success.yaml'))
  learn_fail_fpaths = list(logs_dir.glob(
    f'{subject_name}_tree_log_learn_phase_fail.yaml'))

  if apply_success_fpaths or apply_fail_fpaths:
    assert len(apply_success_fpaths) + len(apply_fail_fpaths) == 1, 'apply phase: success XOR fail expected'
    fpaths = apply_success_fpaths + apply_fail_fpaths
    logger.debug(f'Using apply phase log file: {fpaths[0]}')
    return fpaths[0]
  elif learn_success_fpaths or learn_fail_fpaths:
    assert len(learn_success_fpaths) + len(learn_fail_fpaths) == 1, 'learn phase: success XOR fail expected'
    fpaths = learn_success_fpaths + learn_fail_fpaths
    logger.debug(f'Using learn phase log file: {fpaths[0]}')
    return fpaths[0]
  else:
    logger.warning(f'No log file found for subject {subject_name} in {logs_dir}')
    return None


def get_subject_log_fpath(subject_name: str, logs_dir: Path) -> Optional[Path]:
  '''
  Returns the path to "{subject_name}.log" file in logs_dir.
  '''
  log_fpaths = list(logs_dir.glob(f'{subject_name}.log'))
  if len(log_fpaths) == 0:
    logger.warning(f'No log file found for subject {subject_name} in {logs_dir}')
    return None
  assert len(log_fpaths) == 1, 'Expected exactly one log file per subject'
  return log_fpaths[0]


def get_subject_names(args) -> List[str]:
  '''
  Retrieves subject names from file.
  '''
  subject_names_fpath = _normalize_path(args.subject_names_fpath)
  if not subject_names_fpath.exists():
    logger.warning(f'Subject names file not found: {subject_names_fpath}')
    return []

  logger.info(f'Using subject names from {subject_names_fpath}')
  with open(subject_names_fpath, 'r') as f:
    subject_names = [line.strip() for line in f if line.strip()]
  if len(subject_names) == 0:
    logger.warning(f'No subject names found in {subject_names_fpath}')
  return subject_names


# PRIMITIVE STATS
def get_error_from_log(log_fpath: Path) -> str:
  '''
  Extracts error message from a log file.
  Log files must be present in logs_dir.
  First run `make split` to split the main log file into per-subject logs.
  NOTE hard-coded line numbers!
  '''
  assert log_fpath is not None, 'log_fpath should not be None (run `make split` first?)'
  log_text = p_utils.read_text(log_fpath).strip()
  error_line = log_text.splitlines()[-3]
  chunks = error_line.split(' ')[4:]
  assert len(chunks) > 0, 'Expected error message in log file'
  return ' '.join(chunks)


def mode_primitive(args) -> None:
  '''
  (LEARN, APPLY, ERROR) for each subject.
  '''
  output_fpath = args.output_fpath or (p_consts.EXPERIMENTS_DIR / 'primitive-stats.txt')
  output_fpath = _normalize_path(output_fpath)
  fout = open(output_fpath, 'w')

  subject_names = get_subject_names(args)
  for idx, subject_name in enumerate(subject_names, start=1):
    logger.info(f'Processing subject {idx}/{len(subject_names)}: {subject_name}')

    tree_log_fpath = get_subject_tree_log_fpath(subject_name, _normalize_path(args.logs_dir))
    log_fpath = get_subject_log_fpath(subject_name, _normalize_path(args.logs_dir))

    if tree_log_fpath is None:
      fout.write('killed\tn/a\n')
      continue

    lsubject = load_lsubject(tree_log_fpath)
    learn_phase_success, apply_phase_success = lsubject.get_primitive_stats()
    assert learn_phase_success in [True, False, None], 'learn_phase_success should be True, False, or None'
    assert apply_phase_success in [True, False, None], 'apply_phase_success should be True, False, or None'

    if learn_phase_success is True:
      if apply_phase_success is True:
        fout.write('TRUE\tTRUE\n')
      elif apply_phase_success is False:
        error = get_error_from_log(log_fpath)
        fout.write(f'TRUE\tFALSE\t{error}\n')
      elif apply_phase_success is None:
        fout.write('TRUE\tkilled\n')
    elif learn_phase_success is False:
      assert apply_phase_success is None, 'apply_phase_success should be None if learn_phase_success is not True'
      error = get_error_from_log(log_fpath)
      fout.write(f'FALSE\tn/a\t{error}\n')
    elif learn_phase_success is None:
      assert apply_phase_success is None, 'apply_phase_success should be None if learn_phase_success is not True'
      fout.write('killed\tn/a\n')

  fout.close()
  logger.debug(f'Primitive stats written to {output_fpath}')


def mode_tokens(args) -> None:
  '''
  (INPUT-TOKENS, OUTPUT-TOKENS) for each subject.
  '''
  output_fpath = args.output_fpath or (p_consts.EXPERIMENTS_DIR / 'tokens-stats.txt')
  output_fpath = _normalize_path(output_fpath)
  fout = open(output_fpath, 'w')

  subject_names = get_subject_names(args)
  for idx, subject_name in enumerate(subject_names, start=1):
    logger.info(f'Processing subject {idx}/{len(subject_names)}: {subject_name}')

    tree_log_fpath = get_subject_tree_log_fpath(subject_name, _normalize_path(args.logs_dir))

    if tree_log_fpath is None:
      fout.write('\n')
      continue

    lsubject = load_lsubject(tree_log_fpath)
    num_input_tokens = lsubject.get_num_input_tokens()
    num_output_tokens = lsubject.get_num_output_tokens()
    fout.write(f'{num_input_tokens}\t{num_output_tokens}\n')

  fout.close()
  logger.debug(f'Token stats written to {output_fpath}')


def get_args():
  parser = argparse.ArgumentParser(description='Analyze results generated by PiREL')
  parser.add_argument('--mode', '-m',
                      help='Mode of operation',
                      choices=['primitive', 'tokens'],
                      required=True)
  parser.add_argument('--subject_names_fpath', '-s',
                      help='Path to a text file containing subject names, one per line',
                      required=False, default=(p_consts.EXPERIMENTS_DIR / 'subject-names.txt'))
  parser.add_argument('--output_fpath', '-o',
                      help='Path to output file.',
                      required=False)
  parser.add_argument('--logs_dir', '-l',
                      help='Path to directory containing PiREL logs.',
                      required=False, default=p_consts.LEARN_RULES_LOGS_DIR)
  return parser.parse_args()


def main():
  args = get_args()
  if args.mode == 'primitive':
    mode_primitive(args)
  elif args.mode == 'tokens':
    mode_tokens(args)
  else:
    raise ValueError(f'Unknown mode: {args.mode}')


if __name__ == '__main__':
  main()
