'''
Analyzes logs generated by p_learn_apply_rules and outputs statistics.
'''


import argparse
from pathlib import Path

import e_common
import p_consts
import p_utils


logger = p_utils.setup_logger(__name__)


# PRIMITIVE STATS
def get_error_from_log(log_fpath: Path) -> str:
  '''
  Extracts error message from a log file.
  Log files must be present in logs_dir.
  First run `make split` to split the main log file into per-subject logs.
  NOTE hard-coded line numbers!
  '''
  assert log_fpath is not None, 'log_fpath should not be None (run `make split` first?)'
  log_text = p_utils.read_text(log_fpath).strip()
  error_line = log_text.splitlines()[-3]
  chunks = error_line.split(' ')[4:]
  assert len(chunks) > 0, 'Expected error message in log file'
  return ' '.join(chunks)


def mode_primitive(args) -> None:
  '''
  Writes a TSV file with columns
  (LEARN, APPLY, ERROR) for each subject.
  '''
  output_fpath = args.output_fpath or (p_consts.EXPERIMENTS_DIR / 'primitive-stats.txt')
  fout = open(output_fpath, 'w')

  subject_names = e_common.load_subject_names(args.subject_names_fpath)
  for idx, subject_name in enumerate(subject_names, start=1):
    yaml_fpath = e_common.get_path_yaml(subject_name, args.logs_dir)
    log_fpath = e_common.get_path_log(subject_name, args.logs_dir)

    if yaml_fpath is None:
      fout.write('killed\tn/a\n')
      continue

    lsubject = e_common.load_subject_from_yaml(yaml_fpath)
    learn_phase_success, apply_phase_success = lsubject.get_primitive_stats()
    assert learn_phase_success in [True, False, None], 'learn_phase_success should be True, False, or None'
    assert apply_phase_success in [True, False, None], 'apply_phase_success should be True, False, or None'

    if learn_phase_success is True:
      if apply_phase_success is True:
        fout.write('TRUE\tTRUE\n')
      elif apply_phase_success is False:
        error = get_error_from_log(log_fpath)
        fout.write(f'TRUE\tFALSE\t{error}\n')
      elif apply_phase_success is None:
        fout.write('TRUE\tkilled\n')
    elif learn_phase_success is False:
      assert apply_phase_success is None, 'apply_phase_success should be None if learn_phase_success is not True'
      error = get_error_from_log(log_fpath)
      fout.write(f'FALSE\tn/a\t{error}\n')
    elif learn_phase_success is None:
      assert apply_phase_success is None, 'apply_phase_success should be None if learn_phase_success is not True'
      fout.write('killed\tn/a\n')

  fout.close()


def mode_tokens(args) -> None:
  '''
  Writes a TSV file with columns
  (INPUT-TOKENS, OUTPUT-TOKENS) for each subject.
  '''
  output_fpath = args.output_fpath or (p_consts.EXPERIMENTS_DIR / 'tokens-stats.txt')
  fout = open(output_fpath, 'w')

  subject_names = e_common.load_subject_names(args.subject_names_fpath)
  for idx, subject_name in enumerate(subject_names, start=1):
    yaml_fpath = e_common.get_path_yaml(subject_name, args.logs_dir)

    if yaml_fpath is None:
      fout.write('\n')
      continue

    lsubject = e_common.load_subject_from_yaml(yaml_fpath)
    num_intok = lsubject.get_num_input_tokens()
    num_outtok = lsubject.get_num_output_tokens()
    fout.write(f'{num_intok}\t{num_outtok}\n')

  fout.close()


def get_args():
  parser = argparse.ArgumentParser(description='Analyze results generated by PiREL')
  parser.add_argument('--mode', '-m',
                      help='Mode of operation',
                      choices=['primitive', 'tokens'],
                      required=True)
  parser.add_argument('--subject_names_fpath', '-s',
                      help='Path to a text file containing subject names, one per line',
                      required=False, default=(p_consts.EXPERIMENTS_DIR / 'subject-names.txt'))
  parser.add_argument('--output_fpath', '-o',
                      help='Path to output file.',
                      required=False)
  parser.add_argument('--logs_dir', '-l',
                      help='Path to directory containing PiREL logs.',
                      required=False, default=p_consts.LEARN_RULES_LOGS_DIR)
  return parser.parse_args()


def main():
  args = get_args()

  if args.subject_names_fpath:
    args.subject_names_fpath = e_common.normalize_path(args.subject_names_fpath)
  if args.output_fpath:
    args.output_fpath = e_common.normalize_path(args.output_fpath)
  if args.logs_dir:
    args.logs_dir = e_common.normalize_path(args.logs_dir)

  if args.mode == 'primitive':
    mode_primitive(args)
  elif args.mode == 'tokens':
    mode_tokens(args)
  else:
    raise ValueError(f'Unknown mode: {args.mode}')


if __name__ == '__main__':
  main()
