'''
Analyzes logs generated by p_learn_apply_rules and outputs statistics.
'''


import argparse
import os
from pathlib import Path

import e_common
import e_consts
import p_consts
import p_utils
import csv


def get_error_from_log(log_fpath: Path) -> str:
  '''
  Extracts error message from a log file.
  Log files must be present in logs_dir.
  First run `make split` to split the main log file into per-subject logs.
  NOTE hard-coded line numbers!
  '''
  assert log_fpath is not None, 'log_fpath should not be None (run `make split` first?)'
  log_text = p_utils.read_text(log_fpath).strip()
  error_line = log_text.splitlines()[-3]
  chunks = error_line.split(' ')[4:]
  assert len(chunks) > 0, 'Expected error message in log file'
  return ' '.join(chunks)


def a01_table_learn_apply_error(args) -> None:
  '''
  Writes a CSV file with columns
  (SUBJECT_NAME, LEARN, APPLY, ERROR) for each subject.
  '''
  logger = p_utils.setup_logger(__name__, args.output_dir / 'a01.log')
  fout = open(args.output_dir / 'a01_table_learn_apply_error.csv', 'w', newline='')
  writer = csv.writer(fout)

  # Write header
  writer.writerow(['SUBJECT_NAME', 'LEARN', 'APPLY', 'ERROR'])

  subject_names = e_common.load_subject_names(args.subject_names_fpath)
  for idx, subject_name in enumerate(subject_names, start=1):
    logger.info(f'Processing subject {idx}/{len(subject_names)}: {subject_name}')

    yaml_fpath = e_common.get_path_yaml(subject_name, args.logs_dir)
    log_fpath = e_common.get_path_log(subject_name, args.logs_dir)

    if yaml_fpath is None:
      writer.writerow([subject_name, 'killed', 'n/a', ''])
      continue

    lsubject = e_common.load_subject_from_yaml(yaml_fpath)
    learn_phase_success, apply_phase_success = lsubject.get_primitive_stats()
    assert learn_phase_success in [True, False, None], 'learn_phase_success should be True, False, or None'
    assert apply_phase_success in [True, False, None], 'apply_phase_success should be True, False, or None'

    if learn_phase_success is True:
      if apply_phase_success is True:
        writer.writerow([subject_name, 'TRUE', 'TRUE', ''])
      elif apply_phase_success is False:
        error = get_error_from_log(log_fpath)
        writer.writerow([subject_name, 'TRUE', 'FALSE', error])
      elif apply_phase_success is None:
        writer.writerow([subject_name, 'TRUE', 'killed', ''])
    elif learn_phase_success is False:
      assert apply_phase_success is None, 'apply_phase_success should be None if learn_phase_success is not True'
      error = get_error_from_log(log_fpath)
      writer.writerow([subject_name, 'FALSE', 'n/a', error])
    elif learn_phase_success is None:
      assert apply_phase_success is None, 'apply_phase_success should be None if learn_phase_success is not True'
      writer.writerow([subject_name, 'killed', 'n/a', ''])

  fout.close()


def a02_table_input_output_tokens(args) -> None:
  '''
  Writes a CSV file with columns
  (SUBJECT_NAME, INPUT-TOKENS, OUTPUT-TOKENS) for each subject.
  '''
  logger = p_utils.setup_logger(__name__, args.output_dir / 'a02.log')
  fout = open(args.output_dir / 'a02_table_input_output_tokens.csv', 'w', newline='')
  writer = csv.writer(fout)

  # Write header
  writer.writerow(['SUBJECT_NAME', 'INPUT-TOKENS', 'OUTPUT-TOKENS'])

  subject_names = e_common.load_subject_names(args.subject_names_fpath)
  for idx, subject_name in enumerate(subject_names, start=1):
    logger.info(f'Processing subject {idx}/{len(subject_names)}: {subject_name}')

    yaml_fpath = e_common.get_path_yaml(subject_name, args.logs_dir)

    if yaml_fpath is None:
      writer.writerow([subject_name, '', ''])
      continue

    lsubject = e_common.load_subject_from_yaml(yaml_fpath)
    num_intok = lsubject.get_num_input_tokens()
    num_outtok = lsubject.get_num_output_tokens()
    writer.writerow([subject_name, num_intok, num_outtok])

  fout.close()


def get_args():
  parser = argparse.ArgumentParser(description='Analyze results generated by PiREL')
  parser.add_argument('--analysis', '-a', metavar='N',
                      help='Analysis id',
                      type=int, required=True)
  parser.add_argument('--subject_names_fpath', '-s', metavar='PATH',
                      help='Path to a text file containing subject names, one per line',
                      required=True)
  parser.add_argument('--logs_dir', '-l', metavar='PATH',
                      help='Path to directory containing PiREL logs.',
                      required=True)
  parser.add_argument('--output_dir', '-o', metavar='PATH',
                      help='Path to output directory.',
                      required=False, default=e_consts.RESULTS_DIR)
  parser.add_argument('--tag', '-t', metavar='STR',
                      help='Tag to append to output directory name.',
                      required=False, type=str, default='')
  return parser.parse_args()


def main():
  args = get_args()

  if args.subject_names_fpath:
    args.subject_names_fpath = e_common.normalize_path(args.subject_names_fpath)
  if args.logs_dir:
    args.logs_dir = e_common.normalize_path(args.logs_dir)
  if args.output_dir:
    args.output_dir = e_common.normalize_path(args.output_dir)

  args.tag = args.tag.strip().replace(' ', '_')
  args.tag = f'-{args.tag}' if args.tag else ''
  args.output_dir = args.output_dir / f'{p_utils.current_time()}{args.tag}'
  os.makedirs(args.output_dir, exist_ok=True)

  if args.analysis == 1:
    a01_table_learn_apply_error(args)
  elif args.analysis == 2:
    a02_table_input_output_tokens(args)
  else:
    raise ValueError(f'Unknown analysis id: {args.analysis}')


if __name__ == '__main__':
  main()
