import csv
import matplotlib.pyplot as plt
import numpy as np
from typing import List

import e_common
import e_consts
import p_consts


def percentage_histogram_as_line_plot_2d(
  series_list: List[List[float]],
  num_bins: int,
  labels: List[str],
  title: str,
  x_label: str,
  y_label: str,
  output_fpath: str,
  colors: List[str] = e_consts.PLT_COLORS,
  markers: List[str] = e_consts.PLT_MARKERS,
) -> None:
  '''
  Create a line plot from 2D data.
  series_list is supposed to have percentage values between 0.0 and 1.0.
  The result is a histogram-like line plot where the x-axis is divided into num_bins bins
  and the y-axis shows the count of values in each bin for each series.

  Args:
    series_list: 2D list where each inner list represents a series of data points.
    num_bins: Number of bins (x-axis points).
    labels: Labels for each series.
    title: Title of the plot.
    x_label: Label for the x-axis.
    y_label: Label for the y-axis.
    output_fpath: File path to save the plot image.
    colors: List of colors for each series.
    markers: List of markers for each series.
  '''
  num_series = len(series_list)
  assert num_series == len(labels), "Number of series must match number of labels"
  assert num_series <= len(colors), "Not enough colors provided"
  assert num_series <= len(markers), "Not enough markers provided"
  assert len(set(len(series) for series in series_list)) == 1, "All series must have the same length"

  # all values are expected to be percentages between 0.0 and 1.0
  for series in series_list:
    assert all(0.0 <= rate <= 1.0 for rate in series), "All rates must be between 0.0 and 1.0"

  bins = [i / num_bins for i in range(num_bins + 1)]  # bins from 0.0 to 1.0

  plt.figure()
  for series, color, label, marker in zip(series_list, colors, labels, markers):
    counts, bin_edges = np.histogram(series, bins=bins)
    plt.plot(bin_edges[:-1], counts, marker=marker, color=color, label=label)

  plt.xlabel(x_label)
  plt.ylabel(y_label)
  plt.title(title)
  plt.grid(True)
  plt.legend()
  plt.savefig(output_fpath)


def line_plot_series(
  series_list: List[List[float]],
  labels: List[str],
  title: str,
  x_label: str,
  y_label: str,
  output_fpath: str,
  colors: List[str] = e_consts.PLT_COLORS,
  markers: List[str] = e_consts.PLT_MARKERS,
) -> None:
  '''
  Draw a line plot for multiple series.
  The result is a line plot where the x-axis is the index of the value in the series
  and the y-axis is the value itself.

  Args:
    series_list: List of series, each a list of y-values.
    labels: List of labels for each series.
    title: Title of the plot.
    x_label: Label for the x-axis.
    y_label: Label for the y-axis.
    output_fpath: File path to save the plot image.
    colors: List of colors for each series.
    markers: List of markers for each series.
  '''
  num_series = len(series_list)
  assert num_series == len(labels), "Number of series must match number of labels"
  assert num_series <= len(colors), "Not enough colors provided"
  assert num_series <= len(markers), "Not enough markers provided"
  assert len(set(len(series) for series in series_list)) == 1, "All series must have the same length"

  plt.figure()
  for idx, (series, color, label, marker) in enumerate(zip(series_list, colors, labels, markers)):
    x = list(range(len(series)))
    plt.plot(x, series, marker=marker, color=color, label=label)

  plt.xlabel(x_label)
  plt.ylabel(y_label)
  plt.title(title)
  plt.grid(True)
  plt.legend()
  plt.savefig(output_fpath)


def rq1_gfg_subtree_trans_success_rate(
  csv_fpaths: List[str],
  model_names: List[str],
  num_bins: int,
  output_fpath: str,
):
  '''
  CSV is expected to have three columns:
  (SUBJECT_NAME, NUMERATOR, DENOMINATOR, ERROR_STR)
  as generated by e_experiments.e03_rq1_gfg_subtree_trans_success_rate()
  '''
  output_fpath = e_common.normalize_path(output_fpath)
  all_success_rates = []
  for csv_fpath in csv_fpaths:
    csv_fpath = e_common.normalize_path(csv_fpath)
    reader = csv.reader(open(csv_fpath, 'r'))
    next(reader)  # Skip header row
    success_rates = []
    for row in reader:
      assert len(row) == 4, 'Expected four columns in CSV file'
      if row[3] != '':  # error string is not empty
        continue
      numerator = int(row[1])
      denominator = int(row[2])
      assert denominator > 0, 'Denominator should be greater than zero'
      success_rate = numerator / denominator
      assert 0.0 <= success_rate <= 1.0, 'Success rate should be between 0.0 and 1.0'
      success_rates.append(success_rate)
    all_success_rates.append(success_rates)

  percentage_histogram_as_line_plot_2d(
    series_list=all_success_rates,
    num_bins=num_bins,
    labels=model_names,
    title='Subtree-level Translation Success Rate Distribution',
    x_label='Subtree-level Translation Success Rate',
    y_label='Count',
    output_fpath=output_fpath,
  )


def rq2_gfg_rule_extractability(
  csv_fpaths: List[str],
  model_names: List[str],
  num_bins: int,
  output_fpath: str,
):
  '''
  CSV is expected to have three columns:
  (SUBJECT_NAME, NUMERATOR, DENOMINATOR, ERROR_STR)
  as generated by e_experiments.e04_rq2_gfg_rule_extractability()
  '''
  output_fpath = e_common.normalize_path(output_fpath)
  all_success_rates = []
  for csv_fpath in csv_fpaths:
    csv_fpath = e_common.normalize_path(csv_fpath)
    reader = csv.reader(open(csv_fpath, 'r'))
    next(reader)  # Skip header row
    success_rates = []
    for row in reader:
      assert len(row) == 4, 'Expected four columns in CSV file'
      if row[3] != '':  # error string is not empty
        continue
      numerator = int(row[1])
      denominator = int(row[2])
      assert denominator > 0, 'Denominator should be greater than zero'
      success_rate = numerator / denominator
      assert 0.0 <= success_rate <= 1.0, 'Success rate should be between 0.0 and 1.0'
      success_rates.append(success_rate)
    all_success_rates.append(success_rates)

  percentage_histogram_as_line_plot_2d(
    series_list=all_success_rates,
    num_bins=num_bins,
    labels=model_names,
    title='Rule Extractability Distribution',
    x_label='Rule Extractability',
    y_label='Count',
    output_fpath=output_fpath,
  )


def rq3_gfg_rule_reusability(
  csv_fpaths: List[str],
  model_names: List[str],
  output_fpath: str,
):
  '''
  CSV is expected to have two columns:
  (COUNT, RULE_STR)
  as generated by e_experiments.e05_rq3_gfg_rule_reusability()

  NOTE rule indices must be consistent across CSV files!
  '''
  output_fpath = e_common.normalize_path(output_fpath)
  assert len(csv_fpaths) == 1, 'reimplement for multiple CSV files'

  all_counts = []
  for csv_fpath in csv_fpaths:
    csv_fpath = e_common.normalize_path(csv_fpath)
    reader = csv.reader(open(csv_fpath, 'r'))
    next(reader)  # Skip header row
    counts = []
    for row in reader:
      assert len(row) == 2, 'Expected two columns in CSV file'
      count = int(row[0])
      counts.append(count)
    # sort reuse rates in ascending order
    counts.sort()
    all_counts.append(counts)

  line_plot_series(
    series_list=all_counts,
    labels=model_names,
    title='Rule Reusability',
    x_label='Rule Index (sorted by reusability)',
    y_label='# of Uses',
    output_fpath=output_fpath,
  )


if __name__ == '__main__':
  # rq1_gfg_subtree_trans_success_rate(
  #   ['experiments/results/2025-09-14-21-54-46-gfg_gpt-5_subtree-trans-success-rate/e03_rq1_gfg_subtree_trans_success_rate.csv'],
  #   ['GPT-5'],
  #   10,
  #   'experiments/subtree-trans-success-rate.png'
  # )
  # rq2_gfg_rule_extractability(
  #   ['experiments/results/2025-09-14-21-58-54-gfg_gpt-5_rule-extractability/e04_rq2_gfg_rule_extractability.csv'],
  #   ['GPT-5'],
  #   10,
  #   'experiments/rule-extractability.png'
  # )
  rq3_gfg_rule_reusability(
    ['experiments/results/2025-09-15-16-37-34-gfg_gpt5_rule-reusability/e05_rq3_gfg_rule_reusability.csv'],
    ['GPT-5'],
    'experiments/rule-reusability.png'
  )
