import csv
import matplotlib.pyplot as plt
import numpy as np
from typing import List

import e_common
import e_consts
import p_consts


def percentage_histogram_as_line_plot_2d(
  data2d: List[List[float]],
  num_bins: int,
  labels: List[str],
  title: str,
  x_label: str,
  y_label: str,
  output_fpath: str,
  colors: List[str] = e_consts.PLT_COLORS,
  markers: List[str] = e_consts.PLT_MARKERS,
) -> None:
  '''
  Create a line plot from 2D data.

  Args:
    data2d: 2D list where each inner list represents a series of data points.
    num_bins: Number of bins (x-axis points).
    labels: Labels for each series.
    title: Title of the plot.
    x_label: Label for the x-axis.
    y_label: Label for the y-axis.
    output_fpath: File path to save the plot image.
    colors: List of colors for each series.
    markers: List of markers for each series.
  '''
  num_series = len(data2d)
  assert num_series == len(labels), "Number of series must match number of labels"
  assert num_series <= len(colors), "Not enough colors provided"
  assert num_series <= len(markers), "Not enough markers provided"

  # all values are expected to be percentages between 0.0 and 1.0
  for series in data2d:
    assert all(0.0 <= rate <= 1.0 for rate in series), "All rates must be between 0.0 and 1.0"

  bins = [i / num_bins for i in range(num_bins + 1)]  # bins from 0.0 to 1.0

  plt.figure()
  for series, color, label, marker in zip(data2d, colors, labels, markers):
    counts, bin_edges = np.histogram(series, bins=bins)
    plt.plot(bin_edges[:-1], counts, marker=marker, color=color, label=label)

  plt.xlabel(x_label)
  plt.ylabel(y_label)
  plt.title(title)
  plt.grid(True)
  plt.legend()
  plt.savefig(output_fpath)


def rq1_gfg_subtree_trans_success_rate(
  csv_fpaths: List[str],
  model_names: List[str],
  num_bins: int,
  output_fpath: str,
):
  '''
  CSV is expected to have three columns:
  (NUMERATOR, DENOMINATOR, ERROR_STR)
  as generated by e_experiments.e03_rq1_gfg_subtree_trans_success_rate()
  '''
  all_success_rates = []
  for csv_fpath in csv_fpaths:
    success_rates = []
    reader = csv.reader(open(csv_fpath, 'r'))
    next(reader)  # Skip header row
    for row in reader:
      assert len(row) == 3, 'Expected three columns in CSV file'
      if row[2] != '':  # error string is not empty
        continue
      numerator = int(row[0])
      denominator = int(row[1])
      assert denominator > 0, 'Denominator should be greater than zero'
      success_rate = numerator / denominator
      assert 0.0 <= success_rate <= 1.0, 'Success rate should be between 0.0 and 1.0'
      success_rates.append(success_rate)
    all_success_rates.append(success_rates)

  percentage_histogram_as_line_plot_2d(
    data2d=all_success_rates,
    num_bins=num_bins,
    labels=model_names,
    title='Subtree-level Translation Success Rate Distribution',
    x_label='Subtree-level Translation Success Rate',
    y_label='Count',
    output_fpath=output_fpath,
  )


if __name__ == '__main__':
  rq1_gfg_subtree_trans_success_rate(
    ['/root/pirel-code/experiments/a.csv'],
    ['GPT-5'],
    10,
    '/root/pirel-code/experiments/a.png'
  )
